### ISSUE TITLE
gt

### ISSUE THREAD

**Issue by frenemycode** [ddz16/py-motmetrics#1]
这个真实的gt和测试的文件具体指什么，我使用ocsort测试一段视频得到了一个txt文件，我还有这段视频的det.txt文件，是用这两个文件进行评估吗

**Comment by ddz16** [comment]
ocsort测试一段视频得到了一个txt文件，这个文件是测试文件。
还有这段视频的det.txt文件，这个文件是真实gt文件。
调整成合适格式就可。
